# Generated by Django 4.1.3 on 2022-11-20 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='review',
        ),
    ]
